### ISSUE TITLE
Can you share the instructions to deploy and run this application?

### ISSUE THREAD

**Issue by saietha** [ruby232/slideme#1]
Do you have any demo site where we can see how ui going to look?

**Comment by ruby232** [comment]
I update documentation [INSTALL.md](https://github.com/ruby232/slideme/blob/master/INSTALL.md, i not speak english please any suggestion are welcome.

**Comment by saietha** [comment]
Thank you for your quick response I am following your install guide I will let you know if I see any issues, will you able to provide any consulting services on this application? We are looking to install this application on our servers and want to do some customizations, please share me your email Id so that I will reach you directly.

**Comment by ruby232** [comment]
Feel free to do customizations, remember this application not finished yet and i need help, any suggestion or code your can do a pull request
